In [1]:
import pandas as pd

ventes = pd.read_csv("../data/raw/ech_annonces_ventes_68.csv", sep=";")

ventes.head()

,idannonce,type_annonceur,typedebien,typedetransaction,etage,surface,surface_terrain,nb_pieces,prix_bien,prix_maison,...,UU2010,REG,DEP,loyer_m2_median_n6,nb_log_n6,taux_rendement_n6,loyer_m2_median_n7,nb_log_n7,taux_rendement_n7,prix_m2_vente
0,hektor-robischung-2862,pr,a,v,0,64,NaN,3,128400,NaN,...,68113,44,68,NaN,NaN,NaN,NaN,NaN,NaN,2006.25
1,apimo-82452515,pr,m,v,0,85,4950.0,4,189000,NaN,...,68000,44,68,NaN,NaN,NaN,NaN,NaN,NaN,2223.53
2,immo-facile-52471952,pr,m,v,0,187,3182.0,9,282900,NaN,...,68000,44,68,NaN,NaN,NaN,NaN,NaN,NaN,1512.83
3,immo-facile-52477215,pr,a,v,0,76,NaN,4,79000,NaN,...,68000,44,68,7.93,3.0,0.092,7.93,3.0,0.092,1039.47
4,ag681088-383601401,pr,m,v,0,90,3071.0,5,317000,NaN,...,68000,44,68,9.77,2.0,0.033,9.77,2.0,0.033,3522.22

In [2]:
ventes.head()

,idannonce,type_annonceur,typedebien,typedetransaction,etage,surface,surface_terrain,nb_pieces,prix_bien,prix_maison,...,UU2010,REG,DEP,loyer_m2_median_n6,nb_log_n6,taux_rendement_n6,loyer_m2_median_n7,nb_log_n7,taux_rendement_n7,prix_m2_vente
0,hektor-robischung-2862,pr,a,v,0,64,NaN,3,128400,NaN,...,68113,44,68,NaN,NaN,NaN,NaN,NaN,NaN,2006.25
1,apimo-82452515,pr,m,v,0,85,4950.0,4,189000,NaN,...,68000,44,68,NaN,NaN,NaN,NaN,NaN,NaN,2223.53
2,immo-facile-52471952,pr,m,v,0,187,3182.0,9,282900,NaN,...,68000,44,68,NaN,NaN,NaN,NaN,NaN,NaN,1512.83
3,immo-facile-52477215,pr,a,v,0,76,NaN,4,79000,NaN,...,68000,44,68,7.93,3.0,0.092,7.93,3.0,0.092,1039.47
4,ag681088-383601401,pr,m,v,0,90,3071.0,5,317000,NaN,...,68000,44,68,9.77,2.0,0.033,9.77,2.0,0.033,3522.22

In [3]:
ventes.info()

<class 'pandas.DataFrame'>
RangeIndex: 27737 entries, 0 to 27736
Data columns (total 59 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   idannonce                27737 non-null  str
 1   type_annonceur           27737 non-null  str
 2   typedebien               27737 non-null  str
 3   typedetransaction        27737 non-null  str
 4   etage                    27737 non-null  int64
 5   surface                  27737 non-null  int64
 6   surface_terrain          11444 non-null  float64
 7   nb_pieces                27737 non-null  int64
 8   prix_bien                27737 non-null  int64
 9   prix_maison              437 non-null    float64
 10  prix_terrain             437 non-null    float64
 11  mensualiteFinance        27737 non-null  int64
 12  balcon                   27737 non-null  int64
 13  eau                      27737 non-null  int64
 14  bain                     27737 non-null  int64
 15  dpeL                     27737 non-null  str
 16  dpeC                     17150 non-null  float64
 17  mapCoordonneesLatitude   27737 non-null  float64
 18  mapCoordonneesLongitude  27737 non-null  float64
 19  annonce_exclusive        27737 non-null  str
 20  nb_etages                14859 non-null  float64
 21  parking                  27 non-null     object
 22  places_parking           10169 non-null  float64
 23  cave                     13247 non-null  object
 24  exposition               27737 non-null  str
 25  ges_class                19716 non-null  str
 26  annee_construction       9458 non-null   float64
 27  nb_toilettes             15436 non-null  float64
 28  nb_terraces              4099 non-null   float64
 29  videophone               135 non-null    object
 30  porte_digicode           4264 non-null   object
 31  surface_balcon           658 non-null    float64
 32  ascenseur                8750 non-null   object
 33  nb_logements_copro       7565 non-null   float64
 34  charges_copro            6677 non-null   float64
 35  chauffage_energie        12571 non-null  str
 36  chauffage_systeme        7627 non-null   str
 37  chauffage_mode           13610 non-null  str
 38  categorie_annonceur      27737 non-null  str
 39  logement_neuf            26998 non-null  str
 40  duree_int                26196 non-null  float64
 41  typedebien_lite          27737 non-null  str
 42  date                     27737 non-null  str
 43  INSEE_COM                27737 non-null  int64
 44  IRIS                     27737 non-null  int64
 45  CODE_IRIS                27737 non-null  int64
 46  TYP_IRIS_x               27737 non-null  str
 47  TYP_IRIS_y               27737 non-null  str
 48  GRD_QUART                27737 non-null  int64
 49  UU2010                   27737 non-null  int64
 50  REG                      27737 non-null  int64
 51  DEP                      27737 non-null  int64
 52  loyer_m2_median_n6       17485 non-null  float64
 53  nb_log_n6                17485 non-null  float64
 54  taux_rendement_n6        17485 non-null  float64
 55  loyer_m2_median_n7       19650 non-null  float64
 56  nb_log_n7                19650 non-null  float64
 57  taux_rendement_n7        19650 non-null  float64
 58  prix_m2_vente            27737 non-null  float64
dtypes: float64(22), int64(15), object(5), str(17)
memory usage: 12.5+ MB

In [4]:
ventes['prix_m2_calcule'] = ventes['prix_bien'] / ventes['surface']
ventes_clean = ventes.drop(columns=['prix_maison', 'prix_terrain'])

In [5]:
ventes_clean.to_csv("../data/processed/ventes_clean.csv", index=False)

In [6]:
import pandas as pd

# Charger le fichier depuis raw
ventes = pd.read_csv("../data/raw/ech_annonces_ventes_68.csv", sep=";")

# Créer une copie pour travailler dessus
ventes_clean = ventes.copy()

In [7]:
# Aperçu des premières lignes
ventes_clean.head()

# Informations sur le type des colonnes et valeurs manquantes
ventes_clean.info()

# Statistiques descriptives pour les colonnes numériques
ventes_clean.describe()

<class 'pandas.DataFrame'>
RangeIndex: 27737 entries, 0 to 27736
Data columns (total 59 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   idannonce                27737 non-null  str
 1   type_annonceur           27737 non-null  str
 2   typedebien               27737 non-null  str
 3   typedetransaction        27737 non-null  str
 4   etage                    27737 non-null  int64
 5   surface                  27737 non-null  int64
 6   surface_terrain          11444 non-null  float64
 7   nb_pieces                27737 non-null  int64
 8   prix_bien                27737 non-null  int64
 9   prix_maison              437 non-null    float64
 10  prix_terrain             437 non-null    float64
 11  mensualiteFinance        27737 non-null  int64
 12  balcon                   27737 non-null  int64
 13  eau                      27737 non-null  int64
 14  bain                     27737 non-null  int64
 15  dpeL                     27737 non-null  str
 16  dpeC                     17150 non-null  float64
 17  mapCoordonneesLatitude   27737 non-null  float64
 18  mapCoordonneesLongitude  27737 non-null  float64
 19  annonce_exclusive        27737 non-null  str
 20  nb_etages                14859 non-null  float64
 21  parking                  27 non-null     object
 22  places_parking           10169 non-null  float64
 23  cave                     13247 non-null  object
 24  exposition               27737 non-null  str
 25  ges_class                19716 non-null  str
 26  annee_construction       9458 non-null   float64
 27  nb_toilettes             15436 non-null  float64
 28  nb_terraces              4099 non-null   float64
 29  videophone               135 non-null    object
 30  porte_digicode           4264 non-null   object
 31  surface_balcon           658 non-null    float64
 32  ascenseur                8750 non-null   object
 33  nb_logements_copro       7565 non-null   float64
 34  charges_copro            6677 non-null   float64
 35  chauffage_energie        12571 non-null  str
 36  chauffage_systeme        7627 non-null   str
 37  chauffage_mode           13610 non-null  str
 38  categorie_annonceur      27737 non-null  str
 39  logement_neuf            26998 non-null  str
 40  duree_int                26196 non-null  float64
 41  typedebien_lite          27737 non-null  str
 42  date                     27737 non-null  str
 43  INSEE_COM                27737 non-null  int64
 44  IRIS                     27737 non-null  int64
 45  CODE_IRIS                27737 non-null  int64
 46  TYP_IRIS_x               27737 non-null  str
 47  TYP_IRIS_y               27737 non-null  str
 48  GRD_QUART                27737 non-null  int64
 49  UU2010                   27737 non-null  int64
 50  REG                      27737 non-null  int64
 51  DEP                      27737 non-null  int64
 52  loyer_m2_median_n6       17485 non-null  float64
 53  nb_log_n6                17485 non-null  float64
 54  taux_rendement_n6        17485 non-null  float64
 55  loyer_m2_median_n7       19650 non-null  float64
 56  nb_log_n7                19650 non-null  float64
 57  taux_rendement_n7        19650 non-null  float64
 58  prix_m2_vente            27737 non-null  float64
dtypes: float64(22), int64(15), object(5), str(17)
memory usage: 12.5+ MB

,etage,surface,surface_terrain,nb_pieces,prix_bien,prix_maison,prix_terrain,mensualiteFinance,balcon,eau,...,UU2010,REG,DEP,loyer_m2_median_n6,nb_log_n6,taux_rendement_n6,loyer_m2_median_n7,nb_log_n7,taux_rendement_n7,prix_m2_vente
count,27737.00000,27737.000000,11444.000000,27737.000000,2.773700e+04,437.000000,437.000000,27737.000000,27737.000000,27737.000000,...,27737.000000,27737.0,27737.0,17485.000000,17485.000000,17485.000000,19650.000000,19650.000000,19650.000000,27737.000000
mean,1.39204,108.343188,1017.414037,4.526301,2.773427e+05,213134.462243,89757.581236,13.232433,0.167610,0.283809,...,68370.913834,44.0,68.0,10.779532,17.011210,0.056380,10.639302,151.035929,0.056315,2624.974439
std,26.84627,60.845498,6694.219735,2.029696,1.861352e+05,71437.516537,47633.302968,139.079554,0.415649,0.541601,...,269.815128,0.0,0.0,2.066664,29.391785,0.083427,1.946427,252.454136,0.081040,1195.389487
min,-1.00000,2.000000,1.000000,1.000000,1.076000e+03,86000.000000,1.000000,0.000000,0.000000,0.000000,...,68000.000000,44.0,68.0,3.080000,1.000000,0.003000,4.780000,1.000000,0.003000,15.590000
25%,0.00000,71.000000,378.000000,3.000000,1.590000e+05,156500.000000,62000.000000,0.000000,0.000000,0.000000,...,68112.000000,44.0,68.0,9.440000,2.000000,0.038000,9.320000,3.000000,0.038000,1870.000000
50%,0.00000,95.000000,589.000000,4.000000,2.420000e+05,199620.000000,87000.000000,0.000000,0.000000,0.000000,...,68403.000000,44.0,68.0,10.530000,6.000000,0.048000,10.380000,18.000000,0.048000,2580.650000
75%,1.00000,130.000000,875.000000,5.000000,3.470000e+05,250010.000000,115800.000000,0.000000,0.000000,1.000000,...,68701.000000,44.0,68.0,11.950000,19.000000,0.066000,11.810000,190.000000,0.066000,3268.480000
max,999.00000,980.000000,431600.000000,43.000000,3.380000e+06,514999.000000,320000.000000,7715.000000,8.000000,10.000000,...,68701.000000,44.0,68.0,23.730000,212.000000,10.496000,23.730000,960.000000,10.773000,79500.000000

In [8]:
ventes.isnull().sum()

idannonce                      0
type_annonceur                 0
typedebien                     0
typedetransaction              0
etage                          0
surface                        0
surface_terrain            16293
nb_pieces                      0
prix_bien                      0
prix_maison                27300
prix_terrain               27300
mensualiteFinance              0
balcon                         0
eau                            0
bain                           0
dpeL                           0
dpeC                       10587
mapCoordonneesLatitude         0
mapCoordonneesLongitude        0
annonce_exclusive              0
nb_etages                  12878
parking                    27710
places_parking             17568
cave                       14490
exposition                     0
ges_class                   8021
annee_construction         18279
nb_toilettes               12301
nb_terraces                23638
videophone                 27602
porte_digicode             23473
surface_balcon             27079
ascenseur                  18987
nb_logements_copro         20172
charges_copro              21060
chauffage_energie          15166
chauffage_systeme          20110
chauffage_mode             14127
categorie_annonceur            0
logement_neuf                739
duree_int                   1541
typedebien_lite                0
date                           0
INSEE_COM                      0
IRIS                           0
CODE_IRIS                      0
TYP_IRIS_x                     0
TYP_IRIS_y                     0
GRD_QUART                      0
UU2010                         0
REG                            0
DEP                            0
loyer_m2_median_n6         10252
nb_log_n6                  10252
taux_rendement_n6          10252
loyer_m2_median_n7          8087
nb_log_n7                   8087
taux_rendement_n7           8087
prix_m2_vente                  0
dtype: int64